@startuml EnigmaMachineCore_Component_Diagram

skinparam monochrome true
skinparam componentStyle uml2

package "EnigmaMachineCore (Executable)" {
    [Main App] as App
}

package "EnigmaCore (Library)" {
    component [EnigmaMachine] as EM
    component [RotorBox] as RB
    component [PlugBoard] as PB
    component [Configuration] as Config

    interface "IAssetProvider" as IAP
    interface "ILogger" as ILOG
}

package "External Dependencies" {
    [CLI11]
    [toml11]
}

' Application Dependencies
App ..> EM : uses
App ..> CLI11 : uses
App ..|> ILOG : implements

' Core Internal Dependencies
EM ..> RB : owns
EM ..> PB : owns
EM ..> IAP : uses
EM ..> ILOG : uses
Config ..> IAP : uses
RB ..> Config : uses (RotorConfig)
RB ..> ILOG : uses

' External Lib Usage
Config ..> toml11 : uses

@enduml
