name = "DefaultReflector"
type = "reflector"
size = 26

[reflector]
map = [
    3,
    2,
    1,
    0,
    7,
    25,
    21,
    4,
    20,
    18,
    17,
    15,
    14,
    23,
    12,
    11,
    24,
    10,
    9,
    22,
    8,
    6,
    19,
    13,
    16,
    5
]
