name = "DefaultRotor3"
type = "rotor"
size = 26

[rotor]
notchPosition = 0
forward = [
     6,
    21,
    18,
    23,
    16,
    13,
     2,
     8,
    12,
    14,
    20,
    25,
     3,
     7,
     4,
    15,
    17,
    19,
    24,
     0,
     9,
     1,
    10,
     5,
    11,
    22
]