name = "DefaultRotor1"
type = "rotor"
size = 26

[rotor]
notchPosition = 0
forward = [
     3,
     6,
    21,
    18,
    10,
     9,
    11,
    23,
    19,
    16,
    15,
    13,
     0,
     1,
     4,
     2,
    24,
     7,
    25,
    12,
    14,
    17,
    20,
    22,
     5,
     8
]
