name = "DefaultRotor2"
type = "rotor"
size = 26

[rotor]
notchPosition = 0
forward = [
     6,
    21,
    18,
    10,
     9,
    11,
    23,
    16,
    13,
     0,
     1,
     2,
     8,
    12,
    14,
    20,
    22,
    25,
     3,
     7,
     4,
     5,
    15,
    17,
    19,
    24
]
